# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'stupid-coverage-badge-generator'
description: 'Generates coverage badges from a percent value'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  percent:
    description: 'Test coverage in percent'
    required: true
  text:
    description: 'Text on the left of the badge'
    required: false
    default: 'coverage'
  output-path:
    description: 'Output path for badge'
    required: false
    default: './badges/badge'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.percent }}
    - ${{ inputs.text }}
    - ${{ inputs.output-path }}
